#!/bin/bash

DIRECTORY=TESTS-C

echo
echo "The file being tested is \"$1\"."
echo "*****************"
echo "Parsing $1."
echo
./Testcmm ./$DIRECTORY/$1
echo
echo "*****************"
echo "Compiling $1."
./compiler ./$DIRECTORY/$1  pa_test.apm
echo
echo "*****************"
./pstack/api pa_test

echo
 
